import typescript from '@rollup/plugin-typescript';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
Please visit the GitHub repository for the source code: https://github.com/YOUR_USERNAME/x-posts-sync (UPDATE THIS LINK)
*/
`;

export default {
  input: 'src/main.ts',
  output: {
    dir: 'dist',
    sourcemap: 'inline',
    format: 'cjs',
    exports: 'default',
    entryFileNames: 'main.js',
    banner,
  },
  external: ['obsidian'],
  plugins: [
    typescript({
      sourceMap: true, 
      inlineSources: true 
    }),
    nodeResolve({ browser: true }),
    commonjs(),
  ],
};
